hifrontendcafe/calomentor

- .gitignore
- README.md
- package.json
- utils/sendEmail.ts
- yarn.lock
Send email function util and add env vars
> Send email function util

- constants/index.ts
- index.ts
- serverless.yml
- services/warningsService.ts
https://excalidraw.com/#json=TtcPLFIXt0c2o8cJjdbWc,ICWZQMCpQjgJFbWD91rAFg
> add new warn schema

- services/mentorshipService.ts
- services/userService.ts
Issues
https://app.clickup.com/t/20ragdy
https://app.clickup.com/t/20ragce
Save timezones of Mentee and Mentor
> Save timezones

- services/warningsService.ts
Issue
https://app.clickup.com/t/20rafhe
Add warning assignee id to the warning service
> Add warning assignee

- serverless.yml
> add some envs

- constants/index.ts
- repository/user.ts
- services/userService.ts
- types/index.ts
- utils/validations.ts
Add token to user and update token if is role is updated
Add isAdmin and isMentor functions.
[Issue Link](https://app.clickup.com/t/20rah8r)
[Issue Link for functions](https://app.clickup.com/t/20rahaa)
> add token to user and update if is role is updated

- constants/index.ts
- repository/mentorship.ts
- repository/warning.ts
- services/warningsService.ts
- types/index.ts
> Refactor Warnings Service

- services/mentorshipService.ts
- types/index.ts
> Refactor feedback mentorship

- services/mentorshipService.ts
Refactor confirmation mentorship
> Refactor confirmation mentorship

- repository/warning.ts
- services/warningsService.ts
- types/index.ts
> Fix get all warnings

- constants/index.ts
- definitions/mentorships-api.yml
- repository/mentorship.ts
- services/mentorship/getAllMentorships.ts
Add admin validations
[Link Issue](https://app.clickup.com/t/1pxn0n8)
> Add admin validations

- constants/index.ts
- services/timeSlots.ts
- utils/dates.ts
Add timeslot validations when create a new one
[Link Issue](https://app.clickup.com/t/1pxn0q0)
> Add timeslots validations

- package.json
- services/mentorship/getAllMentorships.ts
- services/mentorshipService.ts
- utils/dates.ts
- yarn.lock
Delete date-fns and replace all functions
Link Issues: 
[Identificar uso y manejo de fechas en Calomentor](https://app.clickup.com/t/22buufe)
[Reemplazar funcionalidades de la libreria anterior en `utils/dates.ts`](https://app.clickup.com/t/22buua7)
[Desinstalar date-fns y date-fns-tz](https://app.clickup.com/t/22butpu)
[Centralizar uso y manejo de fechas en `utils/dates.ts`](https://app.clickup.com/t/22buuk4)
> delete date-fns and replace all functions

- services/mentorshipService.ts
- services/warningsService.ts
Fix responses of WarningServices and MentorshipServices
> Fix responses

- repository/user.ts
- repository/warning.ts
- services/warningsService.ts
- types/index.ts
Add names to warning data
[Link Issue](https://app.clickup.com/t/22qe3n2)
> add names to warning data

- docs/Calobot.json
> add Calobot Insomnia docs

- package.json
- services/mentorshipService.ts
- utils/ical.ts
- utils/sendEmail.ts
- yarn.lock
Add icalendar to mail
[Link Issue](https://app.clickup.com/t/1qmf9k7)
> Add icalendar to mail

- services/timeSlots.ts
- utils/dates.ts
Fix timeslot validation.
Fix the user can't add a timeslot in same date or 45 minutes after.
> Fix timeslot validation

- repository/user.ts
- repository/warning.ts
- types/index.ts
Fix problem in warning and user data with some properties names.
Change some properties names:
User: 
- timezone => user_timezone
Warning
- status => warning_status
> fix reserved keywords

- constants/index.ts
- repository/user.ts
- services/mentorship/Api/createMentorship.ts
- services/userService.ts
Some random fixes for Calomentor
Add validation for timeslot if is occupied in the creation of a mentorship.
User types fixes. (timezone)
Use promise on the start execution of the state machine.
Types for start execution of the state machine.
Fix when update the userToken for user and we deactivate the mentor.
> Some random fixes for Calomentor

- mails/cancel.ts
- mails/confirmMentorship.ts
- mails/confirmation.ts
- mails/reminder.ts
> Add new mail design

- services/warningsService.ts
- Allow only admins mentors to forgive a warning
> Add admin validation

- definitions/create-mentorship-step-function.yml
- definitions/mentorships-state-machine.yml
- index.ts
- mails/confirmMentorship.ts
- services/mentorship/StepFunction/catcherMentorship.ts
- services/mentorship/StepFunction/checkConfirmMentorship.ts
- services/mentorship/StepFunction/confirmationAttemptMentorship.ts
- services/mentorship/StepFunction/createMentorship.ts
- services/mentorship/index.ts
- types/index.ts
- Add error handling to step functions
- Add new dates for confirmation, reminders and send feedbacks
- Add new function to allow notificate errors
> Add error handling to step functions

- services/mentorship/Api/getAllMentorships.ts
- Cancel mentorship now came with the past mentorships and not with the future mentorships
> Fix cancel mentorships

- services/mentorship/Api/getAllMentorships.ts
> fix: fix get all mentorships

- repository/timeSlot.ts
- services/mentorship/Api/cancelMentorship.ts
- services/mentorship/Api/createMentorship.ts
- services/mentorship/StepFunction/checkConfirmMentorship.ts
- services/mentorship/StepFunction/feedbackFormMentorship.ts
- services/timeSlots.ts
- types/index.ts
> feat: add status to time slots

- services/mentorship/Api/cancelMentorship.ts
- services/mentorship/Api/createMentorship.ts
- services/mentorship/StepFunction/checkConfirmMentorship.ts
- services/mentorship/StepFunction/confirmationAttemptMentorship.ts
- services/mentorship/StepFunction/createMentorship.ts
- services/mentorship/StepFunction/reminderMentorship.ts
- types/index.ts
- utils/ical.ts
> Use mentorship duration

- constants/index.ts
- repository/mentorship.ts
- services/timeSlots.ts
- Disable delete a timeslot when is asociated with a mentorship
> Disable delete a timeslot when is asociated with a mentorship

- repository/timeSlot.ts
- services/timeSlots.ts
- Add get only future timeslots
- Add a filter for not get the canceled by mentor timelots
> Add some new features to get timeslots

- repository/timeSlot.ts
- services/mentorship/Api/cancelMentorship.ts
- services/mentorship/Api/createMentorship.ts
- services/mentorship/StepFunction/checkConfirmMentorship.ts
- services/mentorship/StepFunction/feedbackFormMentorship.ts
- services/timeSlots.ts
> fix: timeslot status import

- definitions/create-mentorship-step-function.yml
- Fix state machine definitions waits
> fix: state machine definition waits

- repository/user.ts
- Add accepted coc field to get users
> add accepted coc to get users

- services/userService.ts
> fix accepted coc

- services/mentorship/StepFunction/createMentorship.ts
- Add more time for mails in test env
> Fix test times

- constants/index.ts
- definitions/mentorships-api.yml
- index.ts
- services/mentorship/Api/createMentorship.ts
- services/mentorship/index.ts
- types/index.ts
Add create mentorship endpoint for matebot.
Issue: 
-  https://app.clickup.com/t/2bfnvgn
> Add create mentorship endpoint for matebot.

- repository/warning.ts
- services/warningsService.ts
- utils/makeResponses.ts
add: get all warnings by mentee id
Issues: 
- https://app.clickup.com/t/2bfnvmr
> add: get all warnings by mentee id

- repository/warning.ts
- services/warningsService.ts
- types/index.ts
> add: forgive author

- services/warningsService.ts
> fix: forgive warning

- constants/index.ts
- definitions/db-tables.yml
- repository/mentorship.ts
- repository/timeSlot.ts
- repository/user.ts
- repository/warning.ts
- serverless-dev.yml
- serverless.yml
- services/mentorship/Api/createMentorship.ts
- services/mentorship/Api/getAllMentorships.ts
- services/userService.ts
- services/warningsService.ts
- utils/dynamoDb.ts
- yarn.lock
Add dates to mentorship and warning matebot services
> add: dates

- constants/index.ts
- definitions/users.yml
- index.ts
- repository/user.ts
- serverless-dev.yml
- serverless.yml
- services/userService.ts
- types/index.ts
Add mentor services from sanity
Issue: https://app.clickup.com/t/2nw1ry5
> Add mentor services

- services/mentorship/Api/createMentorship.ts
Add mentee mail and mentor mail
Issue: https://app.clickup.com/t/2npcj9k
> Add mentee mail and mentor mail

- repository/mentorship.ts
- repository/warning.ts
- services/mentorship/Api/getAllMentorships.ts
- services/warningsService.ts
Issue: 
- https://app.clickup.com/t/2wv83u1
> search by user type
